name: 'Deploy Function App'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'OfirRG-Service-Connection'
  functionAppName: 'ofirFunc'
  projectRoot: 'hit-counter-function'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.12'
  inputs:
    versionSpec: '3.12'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r $(projectRoot)/requirements.txt --target=$(projectRoot)/.python_packages/lib/site-packages
  displayName: 'Install Python dependencies'

- task: AzureFunctionApp@1
  displayName: 'Deploy Azure Function App'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appType: 'functionAppLinux'
    appName: '$(functionAppName)'
    package: '$(projectRoot)'
    deploymentMethod: 'runFromPackage'
